# Generated by Django 4.2.30 on 2026-06-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('nickname', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
